PACKAGE_NAME="qat"
PACKAGE_VERSION="4.28.0-00004"
AUTOINSTALL="yes"

MAKE[0]="./scripts/dkms-build.sh ${kernel_source_dir} ${kernelver}"
CLEAN="test ! -f Makefile || make clean"

BUILT_MODULE_NAME[0]="intel_qat"
BUILT_MODULE_LOCATION[0]="build/"
DEST_MODULE_LOCATION[0]="/updates/dkms"

BUILT_MODULE_NAME[1]="qat_api"
BUILT_MODULE_LOCATION[1]="build/"
DEST_MODULE_LOCATION[1]="/updates/dkms"

BUILT_MODULE_NAME[2]="usdm_drv"
BUILT_MODULE_LOCATION[2]="build/"
DEST_MODULE_LOCATION[2]="/updates/dkms"

BUILT_MODULE_NAME[3]="qat_dh895xcc"
BUILT_MODULE_LOCATION[3]="build/"
DEST_MODULE_LOCATION[3]="/updates/dkms"

BUILT_MODULE_NAME[4]="qat_c62x"
BUILT_MODULE_LOCATION[4]="build/"
DEST_MODULE_LOCATION[4]="/updates/dkms"

BUILT_MODULE_NAME[5]="qat_dh895xccvf"
BUILT_MODULE_LOCATION[5]="build/"
DEST_MODULE_LOCATION[5]="/updates/dkms"

BUILT_MODULE_NAME[6]="qat_c62xvf"
BUILT_MODULE_LOCATION[6]="build/"
DEST_MODULE_LOCATION[6]="/updates/dkms"
